name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest
        with:
          useLocalCache: true

      - name: Configure 
        run: cmake --preset default

      - name: Build tests
        run: cmake --build --preset tiny-aes_ut
      
      - name: Run Tests
        run: ctest --preset default